"""
pdf_generator.py
----------------
Generates a professional PDF report for Care Coordination using fpdf2.
"""

from fpdf import FPDF
import os
from datetime import datetime

class CareCoordinationPDF(FPDF):
    def header(self):
        # Arial bold 15
        self.set_font("helvetica", "B", 15)
        # Move to the right
        self.cell(80)
        # Title
        self.cell(30, 10, "Patient Attendance Intelligence Console", align="C")
        # Line break
        self.ln(10)
        self.set_font("helvetica", "I", 10)
        self.cell(0, 10, f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M')}", align="R")
        self.ln(15)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        # Arial italic 8
        self.set_font("helvetica", "I", 8)
        # Page number
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")

def create_pdf_report(patient_data: dict, risk_assessment: dict, plan: str, filename: str = "care_report.pdf") -> str:
    pdf = CareCoordinationPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # --- Patient Details ---
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(13, 27, 42)  # Dark blue
    pdf.cell(0, 10, "Patient Summary", border="B", ln=True)
    pdf.ln(5)
    
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(0, 0, 0)
    
    # Format conditions
    conds = []
    if patient_data.get("hipert"): conds.append("Hypertension")
    if patient_data.get("diab"): conds.append("Diabetes")
    if patient_data.get("schol"): conds.append("Scholarship")
    cond_str = ", ".join(conds) if conds else "None"
    
    details = [
        f"Age: {patient_data.get('age')} years | Gender: {patient_data.get('gender')}",
        f"Lead Time: {patient_data.get('awaiting')} days | SMS Sent: {'Yes' if patient_data.get('sms') else 'No'}",
        f"Conditions: {cond_str}",
        f"Disability Level: {patient_data.get('hcap')}",
        f"Previous No-Shows: {patient_data.get('prev_miss')}",
    ]
    for d in details:
        pdf.cell(0, 6, f"- {d}", ln=True)
    pdf.ln(5)
    
    # --- Risk Assessment ---
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(13, 27, 42)
    pdf.cell(0, 10, "Risk Assessment", border="B", ln=True)
    pdf.ln(5)
    
    pdf.set_font("helvetica", "B", 10)
    tier = risk_assessment.get("risk_tier", "UNKNOWN")
    prob_pct = risk_assessment.get("risk_score", 0) * 100
    
    if tier == "LOW":
        pdf.set_text_color(22, 163, 74)
    elif tier == "MEDIUM":
        pdf.set_text_color(245, 158, 11)
    else:
        pdf.set_text_color(220, 38, 38)
        
    pdf.cell(0, 6, f"Risk Tier: {tier} ({prob_pct:.1f}% probability of no-show)", ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)
    
    # --- Plan ---
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(13, 27, 42)
    pdf.cell(0, 10, "Analysis & Intervention Plan", border="B", ln=True)
    pdf.ln(5)
    
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(0, 0, 0)
    
    # Encode correctly for FPDF standard fonts, or just ignore non-latin-1
    text = plan.encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 6, text)
    pdf.ln(10)
    
    # --- Disclaimer ---
    pdf.set_font("helvetica", "I", 8)
    pdf.set_text_color(100, 100, 100)
    disclaimer = (
        "Ethical Disclaimer: This report is generated by an AI-powered decision support system using "
        "historical data patterns. Interventions must be reviewed and approved by qualified healthcare "
        "administrative staff before implementation. This system does not provide medical advice."
    )
    pdf.multi_cell(0, 5, disclaimer)
    
    out_path = os.path.join(os.path.dirname(__file__), filename)
    pdf.output(out_path)
    return out_path
